default: &default
  adapter: redis
  url: redis://localhost:6379/1

development:
  <<: *default

test:
  <<: *default

production:
  adapter: redis
  url: redis://red-ch8skumkobicv5pj8k5g:6379
  channel_prefix: api_production